app/routes.php
<?php

use DisatCorp\Listeners\EmailNotifier;

Event::listen('DisatCorp.*', EmailNotifier::class);

Event::listen('DisatCorp.Events.BillWasCreated', function($event)
{
    var_dump('Send a notification email to the job creator.');
});

    $routes_path = app_path().'/routes';

    Route::when('*', 'csrf', ['post', 'put', 'patch']);
    Route::controller('password', 'RemindersController');


    foreach(File::files($routes_path) as $file) {
        require_once $file;
    }

app/models/Card.php
<?php

class Card extends \Eloquent
{
	protected $guarded = ['id'];

	public function user()
	{
		return $this->belongsTo(User::class);
	}

	public function getFullNameAttribute()
	{
		return $this->attributes->first_name.' '.$this->last_name;
	}

	public function getExpiratonAttribute()
	{
		return $this->expiration_month.'/'.$this->expiration_year;
	}

	public static function boot()
	{
		self::created(function($card){

			self::finalizeCard($card);
		});

		parent::boot();
	}

	/**
	 * Store he card correctly
	 * @param $card
	 */
	public static function finalizeCard($card)
	{
		$card->code = $card->last_four;
		$card->last_four = substr($card->code, strlen($card->code) - 4);

		for ($i = strlen($card->code) - 4; $i > 0; $i--) {
			$card->last_four = '*' . $card->last_four;
		}

		$card->save();
	}
}

app/models/User.php
<?php

use DisatCorp\Api\Helpdesk\HelpdeskTrait;
use DisatCorp\Api\Permissions\PermissionTrait;
use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;
use \Illuminate\Database\Eloquent\SoftDeletingTrait;

class User extends Eloquent implements UserInterface, RemindableInterface {

    use UserTrait, RemindableTrait, PermissionTrait, SoftDeletingTrait, HelpdeskTrait;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    protected $fillable = [
        'fname', 'lname', 'password',
        'email', 'confirmation_code'
    ];

    protected $dates = ['deleted_at'];


    protected $softDelete = true;

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = array('password', 'remember_token');

    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = Hash::make($password);
    }

    public function getFullName()
    {
        return "{$this->attributes['lname']}, {$this->attributes['fname']}";
    }

    public function getFullNameAttribute()
    {
        return $this->getFullName();
    }

    public function roles()
    {
        return $this->belongsToMany('Role');
    }

    public function clienTickets()
    {
        return $this->hasMany(Ticket::class);
    }

    public function asignedTickets()
    {
        return $this->belongsToMany(Ticket::class);
    }

    public function packages()
    {
        return $this->hasMany(Package::class);
    }


    public static function getAdmins()
    {
        return Role::whereName('admin')
            ->first()
            ->users()->get();
    }


    public static function scopeClientService($query)
    {
        return $query->join('role_user', 'users.id', '=', 'role_user.user_id')
            ->where('role_user.role_id', 2)
            ->orWhere('role_user.role_id', 4)
            ->get();
    }

    // Profile Relations

    public function addresses()
    {
        return $this->hasMany(Address::class);
    }

    public function phones()
    {
        return $this->hasMany(Phone::class);
    }

    public function cards()
    {
        return $this->hasMany(Card::class);
    }


}

app/controllers/UserController.php
<?php

class UserController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 * GET /user
	 *
	 * @return Response
	 */
	public function index()
	{
		return View::make('configurations.users.index')
            ->withUsers(User::all());
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /user/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		if($id > 0) {
            $user = User::find($id);
        }

        if($user) {
            return View::make('configurations.users.edit')
                ->withRoles(Role::orderBy('id', 'DESC')->lists('name', 'id'))
                ->withUser($user);
        }

        return Redirect::back();
	}

    /**
     * Update the specified resource in storage.
     * PUT /user/{id}
     *
     * @internal param int $id
     * @return Response
     */
	public function update()
	{
        if(Input::has('user_id')) {
            $user = User::find(Input::get('user_id'));
            $user->update(Input::all());
            $user->revokeAllRoles();
            $user->addRoles(Input::get('add_roles'));
            $user->save();
            Flash::success("Usuario: {$user->getFullName()} modificado.");
            return Redirect::route('user.index');
        }

        Flash::success("Error Actualizando al usuario.");
        return Redirect::back()
            ->withInputs(Input::all());
	}

	/**
	 * Remove the specified resource from storage.
	 * DELETE /user/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$user = User::find($id);
        if($user) {
            $user->delete();
        }
	}

    public function findByName() {
        return User::get(['id', 'email as name']);
    }

}

app/views/users/payment/add-card.blade.php
<div class="row">
    <div class="col-xs-12 col-sm-6">
        <div class="form-group">
            <label>Nombre</label>
            {{ Form::text('first_name', null, ['class' => 'form-control']) }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-6">
        <div class="form-group">
            <label>Apellido</label>
            {{ Form::text('last_name', null, ['class' => 'form-control']) }}
        </div>
    </div>
</div>
<input type="hidden" value="{{ Auth::user()->id }}" name="user_id">
<div class="row">
    <div class="col-xs-12 col-sm-6">
        <div class="form-group">
            <label>Código</label>
            {{ Form::text('last_four', null, [
                'class' => 'form-control',
                'id' => 'card-code',
                'data-url' => route('card.get-type', ':code')
              ]) }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-6">
        <div class="form-group">
            <label>Identificador</label>
            {{ Form::text('identifier', null, ['class' => 'form-control']) }}
            <p class="help-block">
                Introduzca una palabra que le ayuda a identificar esta tarjeta en su lista.
            </p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-6">
        <label>Fecha de Expiración</label>
        <div class="row">
            <div class="col-xs-4 col-sm-6">
                <div class="form-group">
                    <select class="selectpicker" name="expiration_month" title="Selecione un mes..." data-width="auto">
                        @foreach(Config::get('profile.months') as $id => $month)
                            <option {{ (isset($card)) && ($card->expiration_month == $id) ? 'selected' : ''}}
                                    value="{{ $id }}">{{ $month }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <select class="selectpicker" name="expiration_year" title="Selecione un año..." data-width="auto">
                        @foreach(Config::get('profile.years') as $id => $year)
                            <option {{ (isset($card)) && ($card->expiration_year == $id) ? 'selected' : ''}}
                                    value="{{ $id }}">{{ $year }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-5">
            <div class="form-group">
                <label>Código de Seguridad</label>
                {{ Form::text('security_code', null, ['class' => 'form-control']) }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-5">
            <div class="form-group">
                <label>Tipo</label>
                {{ Form::text('type', null, [
                     'class' => 'form-control',
                     'id' => 'card-type'
                     ])
                 }}
            </div>
        </div>
    </div>
</div>

app/views/users/payment/create.blade.php
@if( isset($card) )
    {{ Form::model($card, [
        'route' => ['users.profile.card.update', $card->id],
        'role' => 'form',
        'method' => 'put'
        ]) }}

    @include('users.payment.fields')

    {{ Form::close() }}
@else
    {{ Form::open([
        'route' => 'users.profile.card.store',
        'role' => 'form',
        'method' => 'post'
        ]) }}

    @include('users.payment.fields')

    {{ Form::close() }}
@endif

app/views/users/payment/fields.blade.php
<div class="panel panel-red">
    <div class="panel-heading">
        <a href="{{ URL::previous() }}" class="btn btn-default btn-xs">
            <i class="fa fa-arrow-left"></i> Atras
        </a>
        <span class="pull-right">Agregar Tarjeta de Crédito</span>
    </div>
    <div class="panel-body">
        @include('users.payment.add-card')
    </div>

    <div class="panel-footer">
        <button class="btn btn-default" type="submit" >
            <i class="fa fa-save"></i> Guardar
        </button>
    </div>
</div>

app/views/users/payment/get-card-request.blade.php
<script>

    $(document).ready(function(){
        $('#card-code').on('change', function(){
            var aero = new AeroprontoAsync();

            var options = {
                url: $(this).data('url').replace(':code', $(this).val()),
                type: 'GET'
            };

            aero.asyncRequest(options, function(response){
                $('#card-type').val(response.data);
            });
        });
    });

</script>

app/views/users/payment/index.blade.php
<div class="panel panel-red">
    <div class="panel-heading">
        Tarjeta de Crédito

        <div class="btn-group pull-right">
            <a href="{{ route('users.profile.card.create') }}" class="btn btn-default btn-xs" >
                <i class="fa fa-plus"></i> Agregar Tarjeta de Crédito
            </a>
        </div>
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-hover" id="card">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Identificador</th>
                    <th>Código</th>
                    <th>Expiración</th>
                    <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                @forelse($cards as $card)
                    <tr>
                        <td>{{ $card->id }}</td>
                        <td>{{ $card->identifier }}</td>
                        <td>{{ $card->last_four }}</td>
                        <td>{{ $card->expiraton }}</td>
                        <td>
                            <div>
                                <a href="#" data-toggle="modal" data-target="#confirm">
                                    <i data-method="post" data-uri="{{ route('users.profile.card.destroy', $card->id) }}" class="fa fa-trash fa-2x"></i>
                                </a>
                                <a href="{{ route('users.profile.card.edit', $card->id) }}">
                                    <i class="fa fa-pencil fa-2x"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                @empty
                    <tr>
                        No hay data
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>

</div>