app/routes.php
<?php

use DisatCorp\Listeners\EmailNotifier;

Event::listen('DisatCorp.*', EmailNotifier::class);

Event::listen('DisatCorp.Events.BillWasCreated', function($event)
{
    var_dump('Send a notification email to the job creator.');
});

    $routes_path = app_path().'/routes';

    Route::when('*', 'csrf', ['post', 'put', 'patch']);
    Route::controller('password', 'RemindersController');


    foreach(File::files($routes_path) as $file) {
        require_once $file;
    }

app/models/Card.php
<?php

class Card extends \Eloquent
{
	protected $guarded = ['id'];

	public function user()
	{
		return $this->belongsTo(User::class);
	}

	public function getFullNameAttribute()
	{
		return $this->attributes->first_name.' '.$this->last_name;
	}

	public function getExpiratonAttribute()
	{
		return $this->expiration_month.'/'.$this->expiration_year;
	}

	public static function boot()
	{
		self::created(function($card){

			self::finalizeCard($card);
		});

		parent::boot();
	}

	/**
	 * Store he card correctly
	 * @param $card
	 */
	public static function finalizeCard($card)
	{
		$card->code = $card->last_four;
		$card->last_four = substr($card->code, strlen($card->code) - 4);

		for ($i = strlen($card->code) - 4; $i > 0; $i--) {
			$card->last_four = '*' . $card->last_four;
		}

		$card->save();
	}
}

app/controllers/ReportsController.php
<?php

use DisatCorp\Api\Reports\ReportableTrait;

class ReportsController extends \BaseController {
    use ReportableTrait;

    /**
     * Display a listing of the resource.
     * GET /reports
     *
     * @param $package_id
     * @return Response
     */
	public function printBill($package_id)
	{
        $pdf  = $this->getBill($package_id, 'components.packages.show');
		return $pdf->download('Factura.pdf');
	}

	/**
	 * All packages report
	 * @return \Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse
	 */
	public function packageAll()
	{
		$view = 'reports.pdf.package';

		if( Request::isMethod('POST') )
		{
			if( !Input::has(['from', 'to']) )
			{
				Flash::error('Es necesario elegir un intervalo de fechas');
				return Redirect::back();
			}

			$from = \Carbon\Carbon::parse(Input::get('from'))->toDateString();
			$to = \Carbon\Carbon::parse(Input::get('to'))->toDateString();

			$data = $this->packageReport($from, $to, true);

			if( Input::get('type') == 'pdf' )
				return \PDF::loadView($view, $data)
					->download('packages_from_'.$from.'_to_'.$to.'.pdf');

		} else {
			$data = [
				'report_name' => 'Todos los paquetes',
			];
		}

		return View::make('reports.index', $data);
	}

	/**
	 * All billed packages
	 * @return \Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse
	 */
	public function packageBilled()
	{
		$view = 'reports.pdf.package';

		if( Request::isMethod('POST') )
		{
			if( !Input::has(['from', 'to']) )
			{
				Flash::error('Es necesario elegir un intervalo de fechas');
				return Redirect::back();
			}

			$from = \Carbon\Carbon::parse(Input::get('from'))->toDateString();
			$to = \Carbon\Carbon::parse(Input::get('to'))->toDateString();

			$data = $this->packageReport($from, $to, false);

			if( Input::get('type') == 'pdf' )
				return \PDF::loadView($view, $data)
					->download('billed_packages_from_'.$from.'_to_'.$to.'.pdf');

		} else {
			$data = [
				'report_name' => 'Paquetes Facturados',
			];
		}

		return View::make('reports.index', $data);
	}

	/**
	 * Tickets Report
	 * @return \Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse
	 */
	public function tickets()
	{
		$view = 'reports.pdf.ticket';
		$reportName = 'Reclamaciones no cerradas';

		if( Request::isMethod('POST') )
		{
			if( !Input::has(['from', 'to']) )
			{
				Flash::error('Es necesario elegir un intervalo de fechas');
				return Redirect::back();
			}

			$from = \Carbon\Carbon::parse(Input::get('from'))->toDateString();
			$to = \Carbon\Carbon::parse(Input::get('to'))->toDateString();


			$report = Ticket::where('ticket_status_id', '<>', 2)->get();

			$data = [
				'report_name' => $reportName,
				'report' => $report,
				'from' => $from,
				'to' => $to,
				'view' => $view
			];

			if( Input::get('type') == 'pdf' )
				return \PDF::loadView($view, $data)
					->download('billed_packages_from_'.$from.'_to_'.$to.'.pdf');

		} else {
			$data = [
				'report_name' => $reportName,
			];
		}

		return View::make('reports.index', $data);
	}

	protected function packageReport($from, $to, $all = true)
	{
		$view = 'reports.pdf.package';

		$report = $all
			? PackageAllReport::whereBetween('created_at', [$from, $to])
			: PackageReport::whereBetween('created_at', [$from, $to]);


		$data = [
			'report_name' => 'Todos los paquetes',
			'report' => $report->orderBy('created_at')->get(),
			'from' => $from,
			'to' => $to,
			'view' => $view
		];

		return $data;
	}
}

app/views/reports/index.blade.php
@extends('layouts.main')

@section('css')
    {{ HTML::style('/bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css') }}
@stop


@section('content')
@section('page-title')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Reportes
                    <hr> <small> {{ $report_name }}</small></h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        @stop
        <div class="row">
            <div class="col-lg-{{ isset($report) ? '3' : '8 col-lg-offset-2' }}">
                {{ Form::open(['method' => 'post']) }}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Parametros de reporte

                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="row">
                            <div class='col-md-12'>
                                <div class="form-group">
                                    <label for="datetimepicker6">Desdes</label>
                                    <div class='input-group date' id='datetimepicker6'>
                                        <input type='text' class="form-control" name="from" />
                                        <span class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class='col-md-12'>
                                <div class="form-group">
                                    <label for="datetimepicker7">Hasta</label>
                                    <div class='input-group date' id='datetimepicker7'>
                                        <input type='text' class="form-control" name="to"/>
                                        <span class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Formato del Reporte</label>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="type"  value="html" checked>Html
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="type" value="pdf">PDF
                                </label>
                            </div>
                        </div>

                    </div>

                    <div class="panel-footer">
                        <button class="btn btn-default" type="submit">Generar</button>
                    </div>
                </div>
                {{ Form::close() }}
            </div>
            <div class="col-lg-9">
                @if( isset($report) )
                    @include($view)
                @endif
            </div>

        </div>
    </div>
@stop

@section('js')
    {{ HTML::script('/bower_components/moment/min/moment.min.js') }}
    {{ HTML::script('/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js') }}
    <script>
        $(function () {
            $('#datetimepicker6').datetimepicker();
            $('#datetimepicker7').datetimepicker({
                useCurrent: false //Important! See issue #1075
            });
            $("#datetimepicker6").on("dp.change", function (e) {
                $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
            });
            $("#datetimepicker7").on("dp.change", function (e) {
                $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
            });
        });
    </script>
@stop

app/views/reports/package.blade.php
<div class="panel panel-default">
    <div class="panel-heading">
        {{ !isset($from) ?: 'Desde '.$from }}
        {{ !isset($to) ?: 'Hasta '.$to }}
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-hover" id="card">
                <thead>
                <tr>
                    <th>Tracking</th>
                    <th>Cliente</th>
                    <th>Estado</th>
                    <th>Fecha</th>
                </tr>
                </thead>
                <tbody>
                @forelse($report as $package)
                    <tr>
                        <td>{{ $package->tracking }}</td>
                        <td>{{ $package->client }}</td>
                        <td>{{ $package->estado }}</td>
                        <td>{{ $package->created_at }}</td>
                    </tr>
                @empty
                    <tr>
                        No hay data
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
    </div>

    <div class="panel-footer">


    </div>

    <!--div class="panel-footer">
</div-->
</div>

app/views/reports/ticket.blade.php
<div class="page-header">
    {{ !isset($from) ?: 'Desde '.$from }}
    {{ !isset($to) ?: 'Hasta '.$to }}
</div>
<hr>
<div class="table-responsive">
    <table class="table table-hover" id="card">
        <thead>
        <tr>
            <th>#</th>
            <th>Cliente</th>
            <th>Estado</th>
            <th>Prioridad</th>
            <th>Creado en</th>
            <th>Aisgnado</th>
        </tr>
        </thead>
        <tbody>
        @forelse($report as $ticket)
            <tr>
                <td>{{ $ticket->id }}</td>
                <td>{{ $ticket->user->full_name }}</td>
                <td>{{ $ticket->status->name }}</td>
                <td>{{ $ticket->priority->name }}</td>
                <td>{{ $ticket->created_at->toDateString() }}</td>
                <td>
                    {{ $ticket->is_asigned ? 'Si' : 'No' }}
                    <ul>
                        @if( $ticket->is_asigned )
                            <li>Asignado a</li>
                            @foreach($ticket->users as $user)
                                <li>{{ $user->full_name }}</li>
                            @endforeach
                        @endif
                    </ul>
            </tr>
        @empty
            <tr>
                No hay data
            </tr>
        @endforelse
        </tbody>
    </table>
</div>